//! What part a file plays in the codebase, so review attention can be tiered:
//! source first, then tests and docs, with generated and vendored files collapsed.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileRole {
    #[default]
    Source,
    Test,
    Docs,
    /// Lockfiles, build output, bundles, snapshots, codegen.
    Generated,
    /// Third-party code checked into the repo.
    Vendored,
}

impl FileRole {
    /// Diff lines are mechanical noise: nobody reviews them line by line.
    pub fn is_noise(self) -> bool {
        matches!(self, FileRole::Generated | FileRole::Vendored)
    }

    /// Parse a role name (from `.gitattributes` or a flag).
    pub fn parse(s: &str) -> Option<FileRole> {
        match s.trim().to_ascii_lowercase().as_str() {
            "source" | "src" | "code" => Some(FileRole::Source),
            "test" | "tests" => Some(FileRole::Test),
            "docs" | "doc" | "documentation" => Some(FileRole::Docs),
            "generated" => Some(FileRole::Generated),
            "vendored" | "vendor" => Some(FileRole::Vendored),
            _ => None,
        }
    }
}

/// Detect a file's role from its path, and from its first lines for generated markers.
pub fn detect_role(path: &str, content: &str) -> FileRole {
    if is_vendored_path(path) {
        FileRole::Vendored
    } else if is_generated_path(path) || has_generated_marker(content) {
        FileRole::Generated
    } else if is_test_path(path) {
        FileRole::Test
    } else if is_docs_path(path) {
        FileRole::Docs
    } else {
        FileRole::Source
    }
}

fn segments(path: &str) -> impl Iterator<Item = &str> {
    path.split('/')
}

fn file_name(path: &str) -> &str {
    path.rsplit('/').next().unwrap_or(path)
}

pub fn is_vendored_path(path: &str) -> bool {
    segments(path).any(|s| matches!(s, "node_modules" | "vendor" | "third_party" | "third-party" | "bower_components" | "Pods" | ".yarn"))
}

/// Paths of generated files whose diffs are noise for review.
pub fn is_generated_path(path: &str) -> bool {
    let file = file_name(path);
    matches!(
        file,
        "Cargo.lock" | "package-lock.json" | "yarn.lock" | "pnpm-lock.yaml" | "poetry.lock" | "Pipfile.lock"
            | "go.sum" | "composer.lock" | "Gemfile.lock" | "bun.lockb" | "bun.lock" | "uv.lock" | "flake.lock"
            | "packages.lock.json" | "gradle.lockfile"
    ) || [
        ".min.js", ".min.css", ".map", ".snap", ".pb.go", "_pb2.py", "_pb2_grpc.py", ".pb.h", ".pb.cc",
        ".generated.ts", ".g.dart", ".freezed.dart", "_generated.go", ".designer.cs",
        ".Designer.cs", ".g.cs", ".g.i.cs", "ModelSnapshot.cs",
    ].iter().any(|ext| file.ends_with(ext))
        || [".rlib", ".rmeta", ".o", ".d", ".pyc", ".class"].iter().any(|ext| file.ends_with(ext))
        || path.starts_with("target/debug/") || path.starts_with("target/release/")
        || segments(path).any(|s| matches!(s, ".fingerprint" | "__pycache__" | "dist" | "__generated__" | "__snapshots__"))
}

/// Codegen conventions: Go's `// Code generated … DO NOT EDIT.`, `@generated`, and friends.
fn has_generated_marker(content: &str) -> bool {
    content.lines().take(5).any(|l| {
        let l = l.to_ascii_lowercase();
        (l.contains("code generated") && l.contains("do not edit"))
            || l.contains("@generated")
            || l.contains("<auto-generated")
            || l.contains("autogenerated file")
            || l.contains("this file was automatically generated")
    })
}

pub fn is_test_path(path: &str) -> bool {
    let file = file_name(path);
    let stem = file.split('.').next().unwrap_or(file);
    let dirs: Vec<&str> = segments(path).take(path.split('/').count().saturating_sub(1)).collect();
    let dir_hit = dirs.iter().any(|s| matches!(*s, "test" | "tests" | "__tests__" | "spec" | "specs" | "testdata" | "__mocks__" | "e2e"))
        // C# test projects like `Foo.Tests/`, and Kotlin source sets like `src/commonTest/`.
        || dirs.iter().any(|s| s.contains('.') && [".Tests", ".Test", ".UnitTests", ".IntegrationTests", ".FunctionalTests", ".Specs"].iter().any(|e| s.ends_with(e)))
        || dirs.windows(2).any(|w| w[0] == "src" && w[1].ends_with("Test") && w[1].starts_with(|c: char| c.is_ascii_lowercase()));
    dir_hit
        || file.ends_with("_test.go")
        || (file.ends_with(".py") && (stem.starts_with("test_") || stem.ends_with("_test") || stem == "conftest"))
        || [".test.", ".spec.", "_spec."].iter().any(|m| file.contains(m))
        || (file.ends_with(".java") || file.ends_with(".kt")) && (stem.ends_with("Test") || stem.ends_with("Tests") || stem.ends_with("IT"))
        || file.ends_with(".cs") && (stem.ends_with("Test") || stem.ends_with("Tests"))
        || file.ends_with(".scala") && (stem.ends_with("Test") || stem.ends_with("Tests") || stem.ends_with("Spec") || stem.ends_with("Suite"))
        || path.contains("src/test/")
}

/// A changelog or release notes: `CHANGES.rst`, `CHANGELOG.md`, `HISTORY`, `NEWS`, `RELEASE_NOTES.md`.
pub fn is_changelog_path(path: &str) -> bool {
    let lower = file_name(path).to_ascii_lowercase();
    ["changelog", "changes", "history", "news", "release_notes", "release-notes", "releases"]
        .iter()
        .any(|n| lower == *n || lower.starts_with(&format!("{n}.")))
}

pub fn is_docs_path(path: &str) -> bool {
    let file = file_name(path);
    let lower = file.to_ascii_lowercase();
    let doc_ext = [".md", ".mdx", ".rst", ".adoc", ".txt"].iter().any(|e| lower.ends_with(e));
    let doc_name = ["readme", "changelog", "changes", "contributing", "license", "licence", "notice", "authors", "history"]
        .iter()
        .any(|n| lower == *n || lower.starts_with(&format!("{n}.")));
    let doc_dir = segments(path).take(path.split('/').count().saturating_sub(1)).any(|s| matches!(s, "docs" | "doc" | "documentation"));
    doc_ext || doc_name || (doc_dir && !is_code_ext(&lower))
}

fn is_code_ext(file: &str) -> bool {
    [".rs", ".ts", ".tsx", ".js", ".jsx", ".py", ".go", ".java", ".c", ".h", ".kt", ".kts", ".cs", ".swift", ".rb", ".scala"].iter().any(|e| file.ends_with(e))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roles_by_path() {
        let cases = [
            ("src/lib.rs", FileRole::Source),
            ("crates/x/tests/cli_tests.rs", FileRole::Test),
            ("pkg/server_test.go", FileRole::Test),
            ("app/test_models.py", FileRole::Test),
            ("web/src/Button.test.tsx", FileRole::Test),
            ("src/test/java/com/x/FooTest.java", FileRole::Test),
            ("core/src/main/scala/x/FooSpec.scala", FileRole::Test),
            ("core/src/main/scala/x/Foo.scala", FileRole::Source),
            ("test/Shared.Tests/ParserTests.cs", FileRole::Test),
            ("src/Newtonsoft.Json.Tests/Linq/JArrayAssert.cs", FileRole::Test),
            ("src/Acme.Core/Parser.cs", FileRole::Source),
            ("src/Acme.Core/Form1.Designer.cs", FileRole::Generated),
            ("library/src/commonTest/kotlin/x/Helpers.kt", FileRole::Test),
            ("library/src/commonMain/kotlin/x/Helpers.kt", FileRole::Source),
            ("README.md", FileRole::Docs),
            ("docs/guide/setup.md", FileRole::Docs),
            ("docs/conf.py", FileRole::Source),
            ("Cargo.lock", FileRole::Generated),
            ("web/dist/app.js", FileRole::Generated),
            ("vendor/github.com/x/y.go", FileRole::Vendored),
            ("node_modules/react/index.js", FileRole::Vendored),
            ("src/testing.rs", FileRole::Source),
            ("tests.rs", FileRole::Source),
        ];
        for (path, role) in cases {
            assert_eq!(detect_role(path, ""), role, "{path}");
        }
    }

    #[test]
    fn generated_marker() {
        assert_eq!(detect_role("api/types.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api"), FileRole::Generated);
        assert_eq!(detect_role("src/a.ts", "// hand written\nexport {}"), FileRole::Source);
    }
}
